- numpy는 np.array 함수를 활용 배열을 생성함
-> ndarray 객체
- numpy는 하나의 데이터 type만 배열에 넣을 수 있음
- List와 가장 큰 차이점 -> dynamic typing not supported
- C의 Array를 사용하여 배열을 생성함

numpy 모듈의 호출

In [1]:
import numpy as np

array의 생성

In [3]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]

In [4]:
a = np.array(a, int)
a

array([1, 2, 3, 4, 5])

In [5]:
test_array = np.array(["1", "4", 5.0, 8], float) # String Type의 데이터를 입력해도
test_array

array([1., 4., 5., 8.])

In [6]:
type(test_array)

numpy.ndarray

In [8]:
type(test_array[1]) # Float Type으로 자동 형변환을 실시

numpy.float64

In [9]:
a = [1, 2, 3, 4, 5]
b = [5, 4, 3, 2, 1]
a[0] is b[-1]

True

In [10]:
a = np.array(a)
b = np.array(b)
a[0] is b[-1]

False

In [11]:
test_array.dtype # Array(배열) 전체의 데이터 Type을 반환함

dtype('float64')

In [14]:
a = [[1, 2, 3], [4, 5, 6], [4, 5, 6]]

In [15]:
np.array(a).shape

(3, 3)

array shape

In [16]:
vector = [1, 2, 3, 4]
np.array(vector, int).shape

(4,)

In [17]:
matrix = [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]]
np.array(matrix, int).shape

(3, 4)

In [18]:
tensor = [
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
    [[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]],
]
np.array(tensor, int).shape

(4, 3, 4)

In [19]:
np.array(tensor, int).ndim

3

In [20]:
np.array(tensor, int).size # data의 갯수

48

numpy dtype

In [21]:
a = np.array([[1, 2, 3], [4.5, 5, 6]], dtype=np.int8)

In [22]:
a.dtype

dtype('int8')

In [23]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32).nbytes
# 32bits = 4bytes -> 6 * 4bytes

24

In [24]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.int32).nbytes

24

In [25]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.int8).nbytes
# 8bits = 1bytes -> 6 * 1bytes

6

In [26]:
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float64).nbytes
# 64bits = 8bytes -> 6 * 8bytes

48

reshape

In [27]:
test_matrix = [[1, 2, 3, 4], [1, 2, 5, 8]]
np.array(test_matrix).shape

(2, 4)

In [28]:
np.array(test_matrix).reshape(4, 2)

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [29]:
np.array(test_matrix).reshape(2, 2, 2)

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [30]:
np.array(test_matrix).reshape(8, )

array([1, 2, 3, 4, 1, 2, 5, 8])

In [33]:
np.array(test_matrix).reshape(2, 4).shape

(2, 4)

In [31]:
np.array(test_matrix).reshape(1, -1)

array([[1, 2, 3, 4, 1, 2, 5, 8]])

In [34]:
np.array(test_matrix).reshape(2, -1)

array([[1, 2, 3, 4],
       [1, 2, 5, 8]])

In [35]:
np.array(test_matrix).reshape(1, -1, 2)

array([[[1, 2],
        [3, 4],
        [1, 2],
        [5, 8]]])

flatten()

In [36]:
test_matrix = [[[1, 2, 3, 4], [1, 2, 5, 8]], [[1, 2, 3, 4], [1, 2, 5, 8]]]
np.array(test_matrix)

array([[[1, 2, 3, 4],
        [1, 2, 5, 8]],

       [[1, 2, 3, 4],
        [1, 2, 5, 8]]])

In [37]:
np.array(test_matrix).shape

(2, 2, 4)

In [40]:
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [41]:
np.array(test_matrix).flatten().shape

(16,)

In [42]:
test_example = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_example

array([[1, 2, 3],
       [4, 5, 6]])

In [43]:
test_example[0][2]

3

In [44]:
test_example[0, 2]

3

In [45]:
test_example[0, 0] = 10 # Matrix 0, 0에 10 할당
test_example

array([[10,  2,  3],
       [ 4,  5,  6]])

In [46]:
test_example[1, 2] = 5
test_example[1, 2]

5

In [47]:
test_example

array([[10,  2,  3],
       [ 4,  5,  5]])

slicing

In [48]:
test_example = np.array([[1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8], [1, 2, 5, 8]], int)
test_example

array([[1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8],
       [1, 2, 5, 8]])

In [49]:
test_example[:, 2:]

array([[5, 8],
       [5, 8],
       [5, 8],
       [5, 8]])

In [50]:
test_example[:, 1:3].shape

(4, 2)

In [51]:
test_example[1:2, :2] # two dimensional

array([[1, 2]])

In [52]:
test_example = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]], int)
test_example

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
test_example[1] # one dimensional

array([ 6,  7,  8,  9, 10])

In [54]:
test_example[1:3] # two dimensional

array([[ 6,  7,  8,  9, 10]])

In [55]:
a = np.arange(100).reshape(10, 10)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [56]:
a[:, -1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

arange

In [57]:
list(range(0, 10, 3))

[0, 3, 6, 9]

In [58]:
type(list(range(30)))

list

In [59]:
# arange : List의 range와 같은 효과,
# integer로 0부터 29까지 배열 추출
np.arange(30)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [61]:
np.arange(0, 10, 0.5) # floating point도 표시 가능함

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [62]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [63]:
np.arange(30).reshape(5, 6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

ones, zeros, empty

In [64]:
# 10 - zero vector 생성
np.zeros(shape=(10,), dtype=np.int8) # shape은 항상 튜플로 적어준다

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [65]:
np.zeros((2, 5)) # 2 by 5 - zero matrix 생성

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [66]:
np.ones(shape=(10,), dtype=np.int8)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [67]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [75]:
np.empty(shape=(10,), dtype=np.int8)

array([-96, -79,  24, -66, -57,   1,   0,   0,   0,   0], dtype=int8)

In [79]:
np.empty((10, 5))

array([[             nan,  5.43230922e-312,  6.75881804e-321,
         4.94065646e-324,  2.27270197e-321],
       [ 2.03060980e-321,  4.30825243e-321,  2.03060980e-321,
         4.78255545e-321,  2.03060980e-321],
       [ 5.55329786e-321, -2.59541305e-310,  5.73116149e-321,
         2.03060980e-321,  6.75881804e-321],
       [-2.06427751e-310,  4.80231808e-321,  2.03060980e-321,
         6.73905541e-321, -2.64973614e-310],
       [ 6.77858066e-321,  2.03060980e-321,  6.79834329e-321,
         2.03060980e-321,  6.69953016e-321],
       [ 2.03060980e-321,  9.67114586e-312, -4.22681916e-311,
                     nan,  5.43230922e-312],
       [ 6.73905541e-321,  1.97626258e-323,  6.79834329e-321,
         1.97626258e-323,  4.30825243e-321],
       [-2.75838233e-310,  4.78255545e-321,  9.65508085e-312,
         5.55329786e-321,  9.65508085e-312],
       [ 5.73116149e-321,  9.65508085e-312,  6.75881804e-321,
        -2.81270542e-310,  4.80231808e-321],
       [-2.26947450e-310,  6.73905541

In [80]:
test_matrix = np.arange(100).reshape(5, -1)
test_matrix.shape

(5, 20)

In [81]:
test_matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55,
        56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
        76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95,
        96, 97, 98, 99]])

In [82]:
np.zeros_like(test_matrix, dtype=np.float32)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]], dtype=float32)

In [83]:
np.ones_like(test_matrix, dtype=np.float32)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]], dtype=float32)

In [130]:
np.empty_like(test_matrix, dtype=np.float32)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1.]], dtype=float32)

eye, identity, diagonal

In [131]:
np.identity(n=3, dtype=np.int8)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [132]:
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [133]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [134]:
np.eye(3, 5, k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [135]:
matrix = np.arange(12).reshape(3, 4)
matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [136]:
np.diag(matrix, k=2)

array([2, 7])

In [137]:
np.diag(matrix, k=1)

array([ 1,  6, 11])

In [138]:
np.diag(matrix, k=-1)

array([4, 9])

In [139]:
np.diag(matrix, k=0)

array([ 0,  5, 10])

numpy.random

In [141]:
np.random.uniform(0, 1, 10).reshape(2, 5)

array([[0.05590007, 0.94473186, 0.44396097, 0.00936938, 0.99647757],
       [0.03366915, 0.56470942, 0.42451621, 0.60172603, 0.02769093]])

In [142]:
np.random.normal(0, 1, 10).reshape(2, 5)

array([[-1.05822404, -1.494267  ,  1.82256858,  1.54082348, -0.54734242],
       [-0.87371694, -2.46188944, -2.120693  , -0.61244006,  0.77234709]])

In [144]:
np.random.exponential(scale=2, size=10)

array([0.75815769, 0.89868323, 3.47623808, 0.64253494, 0.46586311,
       2.26879885, 1.60913122, 5.72403864, 1.87780403, 3.56641813])

operation in array

In [146]:
test_array = np.arange(1, 11)
test_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [147]:
test_array.sum()

55

In [148]:
test_array.mean()

5.5

In [149]:
test_array.std()

2.8722813232690143

In [150]:
test_array = np.arange(1, 13).reshape(3, 4) # axis_0, axis_1
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [151]:
test_array.sum(axis=1)

array([10, 26, 42])

In [152]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [153]:
third_order_tensor = np.array([test_array, test_array, test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [155]:
third_order_tensor.shape # axis_0, axis_1, axis_2

(3, 3, 4)

In [156]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [157]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [158]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [161]:
test_array = np.arange(1, 13).reshape(3, 4)
test_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [162]:
test_array.mean(axis=1)

array([ 2.5,  6.5, 10.5])

In [163]:
test_array.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [164]:
test_array.std(axis=1)

array([1.11803399, 1.11803399, 1.11803399])

In [165]:
np.sqrt(test_array)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479, 3.46410162]])

In [166]:
np.exp(test_array)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05]])

concatenate

In [167]:
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a, b))

array([[1, 2, 3],
       [2, 3, 4]])

In [168]:
a = np.array([[1], [2], [3]])
b = np.array([[2], [3], [4]])
np.hstack((a, b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [171]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate((a, b), axis=1) # axis 붙였을 때 새로 생기는 축이라고 생각하면 편하다

array([[1, 2, 3, 2, 3, 4]])

In [172]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5], [6]])
np.concatenate((a, b), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [175]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])
b

array([5, 6])

In [176]:
b.shape

(2,)

In [177]:
b = b[np.newaxis, :]
b

array([[5, 6]])

In [178]:
b.shape

(1, 2)

In [179]:
np.concatenate((a, b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [180]:
test_a = np.array([[1, 2, 3], [4, 5, 6]], float)
test_a

array([[1., 2., 3.],
       [4., 5., 6.]])

element-wise operations

In [181]:
test_a + test_a # Matrix + Matrix 연산

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

In [183]:
test_a - test_a # Matrix - Matrix 연산

array([[0., 0., 0.],
       [0., 0., 0.]])

In [184]:
test_a * test_a # Matrix 내 element들 간 같은 위치에 있는 값들끼리 연산

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [185]:
matrix_a = np.arange(1, 13).reshape(3, 4)
matrix_a - matrix_a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

dot product

In [187]:
test_a = np.arange(1, 7).reshape(2, 3)
test_b = np.arange(7, 13).reshape(3, 2)

In [188]:
test_b

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [189]:
test_a.dot(test_b)

array([[ 58,  64],
       [139, 154]])

transpose

In [190]:
test_a = np.arange(1, 7).reshape(2, 3)
test_a

array([[1, 2, 3],
       [4, 5, 6]])

In [191]:
test_a.transpose()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [192]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [193]:
test_a.T.dot(test_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

broadcasting

In [194]:
test_matrix = np.array([[1, 2, 3], [4, 5, 6]], float)
scalar = 3

In [195]:
test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [196]:
test_matrix + scalar

array([[4., 5., 6.],
       [7., 8., 9.]])

In [197]:
test_matrix - scalar

array([[-2., -1.,  0.],
       [ 1.,  2.,  3.]])

In [198]:
test_matrix * 5

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [199]:
test_matrix / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2]])

In [200]:
test_matrix // 2

array([[0., 1., 1.],
       [2., 2., 3.]])

In [201]:
test_matrix ** 2

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [202]:
test_matrix = np.arange(1, 13).reshape(4, 3)
test_vector = np.arange(10, 40, 10)

In [203]:
test_matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [204]:
test_vector

array([10, 20, 30])

In [205]:
test_matrix + test_vector

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

numpy performance

In [206]:
def sclar_vector_product(scalar, vector):
    result = []
    for value in vector:
        result.append(scalar * value)
    return result 

iternation_max = 100000000

vector = list(range(iternation_max))
scalar = 2

%timeit sclar_vector_product(scalar, vector) # for loop을 이용한 성능

19.3 s ± 2.01 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [207]:
%timeit [scalar * value for value in range(iternation_max)] # list comprehension을 이용한 성능

15.3 s ± 1.01 s per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [208]:
%timeit np.arange(iternation_max) * scalar # numpy를 이용한 성능

521 ms ± 39.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


all & any

In [209]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [210]:
a < 4

array([ True,  True,  True,  True, False, False, False, False, False,
       False])

In [211]:
a < 1

array([ True, False, False, False, False, False, False, False, False,
       False])

In [212]:
a < 10

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [213]:
np.all(a < 10)

True

In [214]:
np.all(a < 5)

False

In [215]:
np.any(a > 5)

True

In [216]:
np.any(a < 0)

False

In [217]:
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)

In [218]:
test_a > test_b

array([False,  True, False])

In [219]:
test_a >= test_b

array([False,  True, False])

In [220]:
(test_a > test_b).any()

True

In [221]:
(test_a > test_b).all()

False

In [223]:
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3)

array([ True, False, False])

In [224]:
b = np.array([True, False, True], bool)
np.logical_not(b)

array([False,  True, False])

In [225]:
c = np.array([False, True, False], bool)
c

array([False,  True, False])

In [226]:
np.logical_or(b, c)

array([ True,  True,  True])

np.where

In [4]:
a = np.array([1, 3, 0], float)
a

array([1., 3., 0.])

In [6]:
np.where(a > 2)

(array([1], dtype=int64),)

In [7]:
np.where(a < 3)[0]

array([0, 2], dtype=int64)

In [8]:
np.where(a < 3, 3, 2) # where(condition, True인 경우, False인 경우)

array([3, 2, 3])

In [9]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [10]:
np.where(a > 10) # 조건 만족하는 index값 반환

(array([6, 7, 8, 9], dtype=int64),)

In [11]:
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [12]:
np.isfinite(a)

array([ True, False, False])

argmax & argmin

In [13]:
a = np.array([1, 2, 4, 5, 8, 78, 23, 3])
a

array([ 1,  2,  4,  5,  8, 78, 23,  3])

In [14]:
a.argsort() # 작은 값부터 index를 뽑아줌

array([0, 1, 7, 2, 3, 4, 6, 5], dtype=int64)

In [15]:
a[a.argsort()]

array([ 1,  2,  3,  4,  5,  8, 23, 78])

In [16]:
a.argsort()[::-1]

array([5, 6, 4, 3, 2, 7, 1, 0], dtype=int64)

In [17]:
np.argmax(a)

5

In [18]:
np.argmin(a)

0

In [19]:
a[np.argmax(a)]

78

In [20]:
a[np.argmin(a)]

1

In [21]:
a = np.array([[1, 2, 4, 7], [9, 88, 6, 45], [9, 76, 3, 4]])
a

array([[ 1,  2,  4,  7],
       [ 9, 88,  6, 45],
       [ 9, 76,  3,  4]])

In [22]:
np.argmax(a, axis=1)

array([3, 1, 1], dtype=int64)

In [23]:
np.argmin(a, axis=0)

array([0, 0, 2, 2], dtype=int64)

boolean index

In [25]:
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [26]:
test_array.shape

(8,)

In [27]:
(test_array > 3).shape

(8,)

In [28]:
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [29]:
condition = test_array < 3
test_array[condition]

array([1., 0., 2.])

fancy index

In [30]:
a = np.array([2, 4, 6, 8], float)
cond = np.array([1, 1, 1, 2, 1, 1, 1, 3])

In [31]:
a[cond]

array([4., 4., 4., 6., 4., 4., 4., 8.])

In [32]:
a.take(cond) # take 함수 : bracket index와 같은 효과

array([4., 4., 4., 6., 4., 4., 4., 8.])

In [33]:
a[a > 4]

array([6., 8.])

In [34]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b, c] # b를 row index, c를 column index로 변환하여 표시함

array([ 1.,  4., 16., 16.,  4.])

In [35]:
a = np.array([[1, 4], [9, 16]], float)
a[b]

array([[ 1.,  4.],
       [ 1.,  4.],
       [ 9., 16.],
       [ 9., 16.],
       [ 1.,  4.]])

data

In [36]:
a = np.loadtxt("./populations.txt", delimiter="\t")
a

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [37]:
a_int = a.astype(int)
a_int[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])

In [38]:
np.savetxt("int_data_2.csv", a_int, fmt="%.2e", delimiter=",")

numpy object - npy

In [39]:
np.save("npy_test", arr=a_int)

In [40]:
a_test = np.load(file="npy_test.npy")
a_test

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500],
       [ 1903, 77400, 35200, 38200],
       [ 1904, 36300, 59400, 40600],
       [ 1905, 20600, 41700, 39800],
       [ 1906, 18100, 19000, 38600],
       [ 1907, 21400, 13000, 42300],
       [ 1908, 22000,  8300, 44500],
       [ 1909, 25400,  9100, 42100],
       [ 1910, 27100,  7400, 46000],
       [ 1911, 40300,  8000, 46800],
       [ 1912, 57000, 12300, 43800],
       [ 1913, 76600, 19500, 40900],
       [ 1914, 52300, 45700, 39400],
       [ 1915, 19500, 51100, 39000],
       [ 1916, 11200, 29700, 36700],
       [ 1917,  7600, 15800, 41800],
       [ 1918, 14600,  9700, 43300],
       [ 1919, 16200, 10100, 41300],
       [ 1920, 24700,  8600, 47300]])

In [41]:
npy_array = np.load(file="npy_test.npy")
npy_array[:3]

array([[ 1900, 30000,  4000, 48300],
       [ 1901, 47200,  6100, 48200],
       [ 1902, 70200,  9800, 41500]])